# необходимо изменить текст данного файла в соответствии с новым интерфейсом

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1377, 855)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Input_and_console = QtWidgets.QVBoxLayout()
        self.Input_and_console.setContentsMargins(0, -1, -1, -1)
        self.Input_and_console.setObjectName("Input_and_console")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.Input_and_console.addWidget(self.label_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_dir.setText("")
        self.lineEdit_dir.setObjectName("lineEdit_dir")
        self.horizontalLayout_5.addWidget(self.lineEdit_dir)
        self.dir_browse = QtWidgets.QPushButton(self.centralwidget)
        self.dir_browse.setObjectName("dir_browse")
        self.horizontalLayout_5.addWidget(self.dir_browse)
        self.Input_and_console.addLayout(self.horizontalLayout_5)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.Input_and_console.addWidget(self.label)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_file = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_file.setObjectName("lineEdit_file")
        self.horizontalLayout_6.addWidget(self.lineEdit_file)
        self.dir2_browse = QtWidgets.QPushButton(self.centralwidget)
        self.dir2_browse.setObjectName("dir2_browse")
        self.horizontalLayout_6.addWidget(self.dir2_browse)
        self.Input_and_console.addLayout(self.horizontalLayout_6)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.Input_and_console.addWidget(self.textBrowser)
        self.convert = QtWidgets.QPushButton(self.centralwidget)
        self.convert.setObjectName("convert")
        self.Input_and_console.addWidget(self.convert)
        self.horizontalLayout.addLayout(self.Input_and_console)
        self.Options = QtWidgets.QGroupBox(self.centralwidget)
        self.Options.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Options.setObjectName("Options")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Options)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.Options)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 829, 845))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        # Делаем опции итогового файла вместо библиотеки
        self.Result_file_options = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.Result_file_options.setObjectName("Result_file_options")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Result_file_options)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        # комбо-бокс с выпадающими вариантами формата итогового файла (docx или gift)
        self.label_format = QtWidgets.QLabel(self.Result_file_options)
        self.label_format.setObjectName("label_format")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_format)
        self.comboBox_format = QtWidgets.QComboBox(self.Result_file_options)
        self.comboBox_format.setObjectName("comboBox_format")
        self.comboBox_format.addItem("")
        self.comboBox_format.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_format)
        self.label_res_file = QtWidgets.QLabel(self.Result_file_options) # имя файла
        self.label_res_file.setObjectName("label_res_file")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_res_file)
        self.lineEdit_res_name = QtWidgets.QLineEdit(self.Result_file_options)
        # self.lineEdit_res_name.setInputMethodHints(QtCore.Qt.ImhNoPredictiveText)
        self.lineEdit_res_name.setObjectName("lineEdit_res_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_res_name)
        self.label_test_name = QtWidgets.QLabel(self.Result_file_options)  # имя теста
        self.label_test_name.setObjectName("label_test_name")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_test_name)
        self.lineEdit_test_name = QtWidgets.QLineEdit(self.Result_file_options)
        self.lineEdit_test_name.setObjectName("lineEdit_test_name")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_test_name)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_4.addWidget(self.Result_file_options)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_display_name_q = QtWidgets.QLabel(self.groupBox)
        self.label_display_name_q.setObjectName("label_display_name_q")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_display_name_q)
        self.lineEdit_display_name_q = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_display_name_q.setObjectName("lineEdit_display_name_q")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_display_name_q)
        # нужно ли добавлять к названиям вопросов их номера
        self.label_allow_numbering = QtWidgets.QLabel(self.groupBox)
        self.label_allow_numbering.setObjectName("label_allow_numbering")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_allow_numbering)
        self.checkBox_allow_numbering = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_allow_numbering.setText("")
        self.checkBox_allow_numbering.setObjectName("checkBox_allow_numbering")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBox_allow_numbering)
        # погрешность - для числовых значений
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.Options)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Questions_converter"))
        self.label_2.setText(_translate("MainWindow", "Введите путь к папке с библиотекой вопросов в xml:"))
        self.dir2_browse.setText(_translate("MainWindow", "Обзор"))
        self.label.setText(_translate("MainWindow", "Введите путь к каталогу, в который будет помещён результат:"))
        self.dir_browse.setText(_translate("MainWindow", "Обзор"))
        self.convert.setText(_translate("MainWindow", "Конвертировать"))
        self.Options.setTitle(_translate("MainWindow", "Настройки"))
        self.Result_file_options.setTitle(_translate("MainWindow", "Файл с вопросами"))
        self.label_format.setText(_translate("MainWindow", "Формат итогового файла (GIFT или DOCX)"))
        self.comboBox_format.setCurrentText("GIFT")
        self.comboBox_format.setItemText(0, "GIFT")
        self.comboBox_format.setItemText(1, "DOCX")
        self.label_res_file.setText(_translate("MainWindow", "Имя файла"))
        self.lineEdit_res_name.setText(_translate("MainWindow", "test_result"))
        self.label_test_name.setText(_translate("MainWindow", "Название теста (для DOCX)"))
        self.lineEdit_test_name.setText(_translate("MainWindow", "Тест."))
        self.groupBox.setTitle(_translate("MainWindow", "Вопросы (всё, кроме погрешности - только для GIFT)"))
        self.label_display_name_q.setText(_translate("MainWindow", "Имя вопроса"))
        self.lineEdit_display_name_q.setText(_translate("MainWindow", "Вопрос"))
        self.label_allow_numbering.setText(_translate("MainWindow", "Нумеровать вопросы в файле"))
        self.label_3.setText(_translate("MainWindow", "Погрешность (где применимо)"))
        self.lineEdit.setText(_translate("MainWindow", "1%"))
